-- =============================================================================
-- Beer Passport — Database Schema
-- =============================================================================
-- Run this against your Supabase project via the SQL editor or supabase CLI:
--   supabase db push
-- =============================================================================

-- Enable UUID extension (usually already enabled on Supabase).
CREATE EXTENSION IF NOT EXISTS "pgcrypto";


-- =============================================================================
-- passport_members
-- Extends Supabase auth.users with passport-specific profile data.
-- =============================================================================
CREATE TABLE IF NOT EXISTS passport_members (
  id            UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  first_name    TEXT        NOT NULL,
  email         TEXT        UNIQUE NOT NULL,
  phone         TEXT,
  member_id     TEXT        UNIQUE NOT NULL, -- Human-readable ID, e.g. ISB-AB12X
  total_visits  INTEGER     NOT NULL DEFAULT 0,
  is_staff      BOOLEAN     NOT NULL DEFAULT FALSE,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Index for staff search by email / phone.
CREATE INDEX IF NOT EXISTS idx_passport_members_email  ON passport_members(email);
CREATE INDEX IF NOT EXISTS idx_passport_members_phone  ON passport_members(phone);
CREATE INDEX IF NOT EXISTS idx_passport_members_mid    ON passport_members(member_id);

-- Row-level security: users can only read/update their own row.
ALTER TABLE passport_members ENABLE ROW LEVEL SECURITY;

CREATE POLICY "members_select_own" ON passport_members
  FOR SELECT USING (auth.uid() = id);

CREATE POLICY "members_insert_own" ON passport_members
  FOR INSERT WITH CHECK (auth.uid() = id);

CREATE POLICY "members_update_own" ON passport_members
  FOR UPDATE USING (auth.uid() = id);


-- =============================================================================
-- rewards
-- Configurable milestone definitions. Staff can update thresholds here.
-- =============================================================================
CREATE TABLE IF NOT EXISTS rewards (
  id               SERIAL      PRIMARY KEY,
  visit_threshold  INTEGER     NOT NULL,
  name             TEXT        NOT NULL,
  description      TEXT        NOT NULL,
  sort_order       INTEGER     NOT NULL DEFAULT 0,
  is_active        BOOLEAN     NOT NULL DEFAULT TRUE
);

-- Everyone can read active rewards (needed for profile progress display).
ALTER TABLE rewards ENABLE ROW LEVEL SECURITY;

CREATE POLICY "rewards_select_all" ON rewards
  FOR SELECT USING (TRUE);


-- =============================================================================
-- check_ins
-- One row per verified visit. Server-authoritative — never touched by client JS.
-- Inserting happens inside the Edge Function only (uses service role).
-- =============================================================================
CREATE TABLE IF NOT EXISTS check_ins (
  id            UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  member_id     UUID        NOT NULL REFERENCES passport_members(id),
  checked_in_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  token_used    TEXT,               -- which QR token was used
  ip_address    TEXT,               -- logged for fraud review
  user_agent    TEXT,               -- logged for fraud review
  is_valid      BOOLEAN     NOT NULL DEFAULT TRUE
);

CREATE INDEX IF NOT EXISTS idx_check_ins_member     ON check_ins(member_id);
CREATE INDEX IF NOT EXISTS idx_check_ins_date       ON check_ins(member_id, checked_in_at);

-- Users can read their own check-ins (for profile display).
-- Inserts are service-role only (Edge Function).
ALTER TABLE check_ins ENABLE ROW LEVEL SECURITY;

CREATE POLICY "checkins_select_own" ON check_ins
  FOR SELECT USING (
    member_id = (SELECT id FROM passport_members WHERE id = auth.uid())
  );


-- =============================================================================
-- qr_tokens
-- Daily rotating tokens. Generated by staff; QR code embeds the token value.
-- =============================================================================
CREATE TABLE IF NOT EXISTS qr_tokens (
  id          UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  token       TEXT        UNIQUE NOT NULL,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  expires_at  TIMESTAMPTZ NOT NULL,
  is_active   BOOLEAN     NOT NULL DEFAULT TRUE,
  created_by  TEXT                  -- staff email/name for audit trail
);

-- Tokens are NOT publicly readable; all access goes through Edge Functions.
ALTER TABLE qr_tokens ENABLE ROW LEVEL SECURITY;
-- No public SELECT policy — service role only.


-- =============================================================================
-- redemptions
-- Tracks which members have claimed which rewards.
-- One row per (member, reward) — duplicate prevention via UNIQUE constraint.
-- Created by staff via the staff portal Edge Function.
-- =============================================================================
CREATE TABLE IF NOT EXISTS redemptions (
  id                UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  member_id         UUID        NOT NULL REFERENCES passport_members(id),
  reward_id         INTEGER     NOT NULL REFERENCES rewards(id),
  redeemed_at       TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  redeemed_by_staff TEXT        NOT NULL, -- staff email for audit trail

  -- Prevent redeeming the same reward twice.
  UNIQUE (member_id, reward_id)
);

CREATE INDEX IF NOT EXISTS idx_redemptions_member ON redemptions(member_id);

-- Users can read their own redemptions.
ALTER TABLE redemptions ENABLE ROW LEVEL SECURITY;

CREATE POLICY "redemptions_select_own" ON redemptions
  FOR SELECT USING (
    member_id = (SELECT id FROM passport_members WHERE id = auth.uid())
  );


-- =============================================================================
-- audit_logs
-- Append-only event log. Written by Edge Functions using service role.
-- Useful for fraud investigation.
-- =============================================================================
CREATE TABLE IF NOT EXISTS audit_logs (
  id          UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  event_type  TEXT        NOT NULL,
  -- Valid event_type values:
  --   signup | login | checkin_attempt | checkin_success | checkin_blocked
  --   reward_redeemed | token_generated | staff_search
  member_id   UUID        REFERENCES passport_members(id),
  details     JSONB,
  ip_address  TEXT,
  user_agent  TEXT,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_audit_member    ON audit_logs(member_id);
CREATE INDEX IF NOT EXISTS idx_audit_event     ON audit_logs(event_type, created_at DESC);

-- Audit logs are NOT readable by regular users.
ALTER TABLE audit_logs ENABLE ROW LEVEL SECURITY;
-- No public SELECT policy — service role only.


-- =============================================================================
-- Seed default rewards
-- Change thresholds / descriptions here or via the Supabase dashboard.
-- =============================================================================
INSERT INTO rewards (visit_threshold, name, description, sort_order) VALUES
  (5,  'Frequent Flyer',  'Free pint on your next visit — you''ve earned it.',            1),
  (10, 'Local Legend',    '10% off your tab — you''re practically family.',               2),
  (20, 'Invasive Regular','Free flight of 5 beers + your name on our Wall of Fame.',      3)
ON CONFLICT DO NOTHING;


-- =============================================================================
-- Helper: increment_visits
-- Called inside the checkin Edge Function to atomically bump total_visits.
-- =============================================================================
CREATE OR REPLACE FUNCTION increment_visits(p_member_id UUID)
RETURNS INTEGER
LANGUAGE plpgsql
SECURITY DEFINER  -- runs with owner privileges so RLS doesn't block it
AS $$
DECLARE
  new_count INTEGER;
BEGIN
  UPDATE passport_members
  SET total_visits = total_visits + 1
  WHERE id = p_member_id
  RETURNING total_visits INTO new_count;

  RETURN new_count;
END;
$$;


-- =============================================================================
-- Helper: get_member_for_staff
-- Lets staff look up a member by email, phone, or member_id without exposing
-- the full members table publicly.
-- =============================================================================
CREATE OR REPLACE FUNCTION get_member_for_staff(p_query TEXT)
RETURNS TABLE (
  id           UUID,
  first_name   TEXT,
  email        TEXT,
  phone        TEXT,
  member_id    TEXT,
  total_visits INTEGER,
  is_staff     BOOLEAN,
  created_at   TIMESTAMPTZ
)
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
  RETURN QUERY
  SELECT
    m.id, m.first_name, m.email, m.phone,
    m.member_id, m.total_visits, m.is_staff, m.created_at
  FROM passport_members m
  WHERE
    m.email    = LOWER(TRIM(p_query)) OR
    m.phone    = TRIM(p_query)        OR
    m.member_id = UPPER(TRIM(p_query));
END;
$$;
